<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE  note[
<!ELEMENT   note (heading,abzac,abzac,foot)>
<!ELEMENT  heading (#PCDATA)>
<!ELEMENT abzac (#PCDATA)>
<!ELEMENT abzac (#PCDATA)>
<!ELEMENT foot (#PCDATA)>
<!ENTITY writer "Donald Duck.">
<!ENTITY copyright "Copyright: дед инсайд">
]>
<note>
<heading>XML document</heading>
<abzac>XML - расширяемый язык разметки.Рекомендован Консорциумом Всемирной паутины (W3C).Спецификация XML описывает XML-документы и частично описывает поведение XML-процессоров (программ, читающих XML-документы и обеспечивающих доступ к их содержимому). XML разрабатывался как язык с простым формальным синтаксисом, удобный для создания и обработки документов как программами, так и человеком, с акцентом на использование в Интернете. Язык называется расширяемым, поскольку он не фиксирует разметку, используемую в документах: разработчик волен создать разметку в соответствии с потребностями к конкретной области, будучи ограниченным лишь синтаксическими правилами языка.</abzac>
<abzac> Расширение XML — это конкретная грамматика, созданная на базе XML и представленная словарём тегов и их атрибутов, а также набором правил, определяющих, какие атрибуты и элементы могут входить в состав других элементов. Сочетание простого формального синтаксиса, удобства для человека, расширяемости, а также базирование на кодировках Юникод для представления содержания документов привело к широкому использованию как, собственно, XML, так и множества производных специализированных языков на базе XML в самых разнообразных программных средствах.</abzac>
<foot>&writer; &copyright;</foot>
</note>